/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGCSHARP


#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_NativeEngineInterop(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_NativeEngineInterop(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_NativeEngineInterop(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else

/*  Errors in SWIG */
#define  SWIG_UnknownError    	   -1 
#define  SWIG_IOError        	   -2 
#define  SWIG_RuntimeError   	   -3 
#define  SWIG_IndexError     	   -4 
#define  SWIG_TypeError      	   -5 
#define  SWIG_DivisionByZero 	   -6 
#define  SWIG_OverflowError  	   -7 
#define  SWIG_SyntaxError    	   -8 
#define  SWIG_ValueError     	   -9 
#define  SWIG_SystemError    	   -10
#define  SWIG_AttributeError 	   -11
#define  SWIG_MemoryError    	   -12 
#define  SWIG_NullReferenceError   -13




#include "../nativeengine.h"
#include "../resourcemanager.h"


SWIGINTERN void SWIG_CSharpException(int code, const char *msg) {
  if (code == SWIG_ValueError) {
    SWIG_CSharpExceptionArgumentCodes exception_code = SWIG_CSharpArgumentOutOfRangeException;
    SWIG_CSharpSetPendingExceptionArgument(exception_code, msg, 0);
  } else {
    SWIG_CSharpExceptionCodes exception_code = SWIG_CSharpApplicationException;
    switch(code) {
    case SWIG_MemoryError:
      exception_code = SWIG_CSharpOutOfMemoryException;
      break;
    case SWIG_IndexError:
      exception_code = SWIG_CSharpIndexOutOfRangeException;
      break;
    case SWIG_DivisionByZero:
      exception_code = SWIG_CSharpDivideByZeroException;
      break;
    case SWIG_IOError:
      exception_code = SWIG_CSharpIOException;
      break;
    case SWIG_OverflowError:
      exception_code = SWIG_CSharpOverflowException;
      break;
    case SWIG_RuntimeError:
    case SWIG_TypeError:
    case SWIG_SyntaxError:
    case SWIG_SystemError:
    case SWIG_UnknownError:
    default:
      exception_code = SWIG_CSharpApplicationException;
      break;
    }
    SWIG_CSharpSetPendingException(exception_code, msg);
  }
}


#include <stdexcept>


#include <string>


#include <Ogre.h>


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void SWIGSTDCALL CSharp_delete_QByteArray(void * jarg1) {
  QByteArray *arg1 = (QByteArray *) 0 ;
  
  arg1 = (QByteArray *)jarg1; 
  {
    try {
      delete arg1;
    } catch(std::exception &e) {
      {
        SWIG_CSharpException(SWIG_UnknownError, e.what()); return ; 
      };
    }
  }
}


SWIGEXPORT int SWIGSTDCALL CSharp_QByteArray_size(void * jarg1) {
  int jresult ;
  QByteArray *arg1 = (QByteArray *) 0 ;
  int result;
  
  arg1 = (QByteArray *)jarg1; 
  {
    try {
      result = (int)(arg1)->size();
    } catch(std::exception &e) {
      {
        SWIG_CSharpException(SWIG_UnknownError, e.what()); return 0; 
      };
    }
  }
  jresult = result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_QByteArray_constData(void * jarg1) {
  char * jresult ;
  QByteArray *arg1 = (QByteArray *) 0 ;
  char *result = 0 ;
  
  arg1 = (QByteArray *)jarg1; 
  {
    try {
      result = (char *)(arg1)->constData();
    } catch(std::exception &e) {
      {
        SWIG_CSharpException(SWIG_UnknownError, e.what()); return 0; 
      };
    }
  }
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_SceneNode_AttachObject(void * jarg1, void * jarg2) {
  Ogre::SceneNode *arg1 = (Ogre::SceneNode *) 0 ;
  Ogre::MovableObject *arg2 = (Ogre::MovableObject *) 0 ;
  
  arg1 = (Ogre::SceneNode *)jarg1; 
  arg2 = (Ogre::MovableObject *)jarg2; 
  {
    try {
      (arg1)->attachObject(arg2);
    } catch(std::exception &e) {
      {
        SWIG_CSharpException(SWIG_UnknownError, e.what()); return ; 
      };
    }
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_SceneNode_CreateChildSceneNode__SWIG_0(void * jarg1) {
  void * jresult ;
  Ogre::SceneNode *arg1 = (Ogre::SceneNode *) 0 ;
  Ogre::SceneNode *result = 0 ;
  
  arg1 = (Ogre::SceneNode *)jarg1; 
  {
    try {
      result = (Ogre::SceneNode *)(arg1)->createChildSceneNode();
    } catch(std::exception &e) {
      {
        SWIG_CSharpException(SWIG_UnknownError, e.what()); return 0; 
      };
    }
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_SceneNode_CreateChildSceneNode__SWIG_1(void * jarg1, char * jarg2) {
  void * jresult ;
  Ogre::SceneNode *arg1 = (Ogre::SceneNode *) 0 ;
  std::string arg2 ;
  Ogre::SceneNode *result = 0 ;
  
  arg1 = (Ogre::SceneNode *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg2)->assign(jarg2); 
  {
    try {
      result = (Ogre::SceneNode *)(arg1)->createChildSceneNode(arg2);
    } catch(std::exception &e) {
      {
        SWIG_CSharpException(SWIG_UnknownError, e.what()); return 0; 
      };
    }
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_SceneNode_setPosition(void * jarg1, float jarg2, float jarg3, float jarg4) {
  Ogre::SceneNode *arg1 = (Ogre::SceneNode *) 0 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  
  arg1 = (Ogre::SceneNode *)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  arg4 = (float)jarg4; 
  {
    try {
      (arg1)->setPosition(arg2,arg3,arg4);
    } catch(std::exception &e) {
      {
        SWIG_CSharpException(SWIG_UnknownError, e.what()); return ; 
      };
    }
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_SceneNode_setOrientation(void * jarg1, float jarg2, float jarg3, float jarg4, float jarg5) {
  Ogre::SceneNode *arg1 = (Ogre::SceneNode *) 0 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  float arg5 ;
  
  arg1 = (Ogre::SceneNode *)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  arg4 = (float)jarg4; 
  arg5 = (float)jarg5; 
  {
    try {
      (arg1)->setOrientation(arg2,arg3,arg4,arg5);
    } catch(std::exception &e) {
      {
        SWIG_CSharpException(SWIG_UnknownError, e.what()); return ; 
      };
    }
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_SceneNode_setScale(void * jarg1, float jarg2, float jarg3, float jarg4) {
  Ogre::SceneNode *arg1 = (Ogre::SceneNode *) 0 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  
  arg1 = (Ogre::SceneNode *)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  arg4 = (float)jarg4; 
  {
    try {
      (arg1)->setScale(arg2,arg3,arg4);
    } catch(std::exception &e) {
      {
        SWIG_CSharpException(SWIG_UnknownError, e.what()); return ; 
      };
    }
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Scene_CreateEntity__SWIG_0(void * jarg1, char * jarg2, char * jarg3) {
  void * jresult ;
  Ogre::SceneManager *arg1 = (Ogre::SceneManager *) 0 ;
  std::string arg2 ;
  std::string arg3 ;
  Ogre::Entity *result = 0 ;
  
  arg1 = (Ogre::SceneManager *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg2)->assign(jarg2); 
  if (!jarg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg3)->assign(jarg3); 
  {
    try {
      result = (Ogre::Entity *)(arg1)->createEntity(arg2,arg3);
    } catch(std::exception &e) {
      {
        SWIG_CSharpException(SWIG_UnknownError, e.what()); return 0; 
      };
    }
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Scene_CreateEntity__SWIG_1(void * jarg1, char * jarg2) {
  void * jresult ;
  Ogre::SceneManager *arg1 = (Ogre::SceneManager *) 0 ;
  std::string arg2 ;
  Ogre::Entity *result = 0 ;
  
  arg1 = (Ogre::SceneManager *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg2)->assign(jarg2); 
  {
    try {
      result = (Ogre::Entity *)(arg1)->createEntity(arg2);
    } catch(std::exception &e) {
      {
        SWIG_CSharpException(SWIG_UnknownError, e.what()); return 0; 
      };
    }
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Scene_CreateSceneNode__SWIG_0(void * jarg1) {
  void * jresult ;
  Ogre::SceneManager *arg1 = (Ogre::SceneManager *) 0 ;
  Ogre::SceneNode *result = 0 ;
  
  arg1 = (Ogre::SceneManager *)jarg1; 
  {
    try {
      result = (Ogre::SceneNode *)(arg1)->createSceneNode();
    } catch(std::exception &e) {
      {
        SWIG_CSharpException(SWIG_UnknownError, e.what()); return 0; 
      };
    }
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Scene_CreateSceneNode__SWIG_1(void * jarg1, char * jarg2) {
  void * jresult ;
  Ogre::SceneManager *arg1 = (Ogre::SceneManager *) 0 ;
  std::string arg2 ;
  Ogre::SceneNode *result = 0 ;
  
  arg1 = (Ogre::SceneManager *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg2)->assign(jarg2); 
  {
    try {
      result = (Ogre::SceneNode *)(arg1)->createSceneNode(arg2);
    } catch(std::exception &e) {
      {
        SWIG_CSharpException(SWIG_UnknownError, e.what()); return 0; 
      };
    }
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_NativeEngineSettings_argc_set(void * jarg1, int jarg2) {
  NativeEngineSettings *arg1 = (NativeEngineSettings *) 0 ;
  int arg2 ;
  
  arg1 = (NativeEngineSettings *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->argc = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_NativeEngineSettings_argc_get(void * jarg1) {
  int jresult ;
  NativeEngineSettings *arg1 = (NativeEngineSettings *) 0 ;
  int result;
  
  arg1 = (NativeEngineSettings *)jarg1; 
  result = (int) ((arg1)->argc);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_NativeEngineSettings_argv_set(void * jarg1, void * jarg2) {
  NativeEngineSettings *arg1 = (NativeEngineSettings *) 0 ;
  char **arg2 = (char **) 0 ;
  
  arg1 = (NativeEngineSettings *)jarg1; 
  arg2 = (char **)jarg2; 
  if (arg1) (arg1)->argv = (char const **)arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_NativeEngineSettings_argv_get(void * jarg1) {
  void * jresult ;
  NativeEngineSettings *arg1 = (NativeEngineSettings *) 0 ;
  char **result = 0 ;
  
  arg1 = (NativeEngineSettings *)jarg1; 
  result = (char **) ((arg1)->argv);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_NativeEngineSettings() {
  void * jresult ;
  NativeEngineSettings *result = 0 ;
  
  {
    try {
      result = (NativeEngineSettings *)new NativeEngineSettings();
    } catch(std::exception &e) {
      {
        SWIG_CSharpException(SWIG_UnknownError, e.what()); return 0; 
      };
    }
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_NativeEngineSettings(void * jarg1) {
  NativeEngineSettings *arg1 = (NativeEngineSettings *) 0 ;
  
  arg1 = (NativeEngineSettings *)jarg1; 
  {
    try {
      delete arg1;
    } catch(std::exception &e) {
      {
        SWIG_CSharpException(SWIG_UnknownError, e.what()); return ; 
      };
    }
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_NativeEngine(void * jarg1) {
  void * jresult ;
  NativeEngineSettings *arg1 = (NativeEngineSettings *) 0 ;
  NativeEngine *result = 0 ;
  
  arg1 = (NativeEngineSettings *)jarg1; 
  {
    try {
      result = (NativeEngine *)new NativeEngine((NativeEngineSettings const *)arg1);
    } catch(std::exception &e) {
      {
        SWIG_CSharpException(SWIG_UnknownError, e.what()); return 0; 
      };
    }
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_NativeEngine(void * jarg1) {
  NativeEngine *arg1 = (NativeEngine *) 0 ;
  
  arg1 = (NativeEngine *)jarg1; 
  {
    try {
      delete arg1;
    } catch(std::exception &e) {
      {
        SWIG_CSharpException(SWIG_UnknownError, e.what()); return ; 
      };
    }
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_NativeEngine_processEvents(void * jarg1) {
  NativeEngine *arg1 = (NativeEngine *) 0 ;
  
  arg1 = (NativeEngine *)jarg1; 
  {
    try {
      (arg1)->processEvents();
    } catch(std::exception &e) {
      {
        SWIG_CSharpException(SWIG_UnknownError, e.what()); return ; 
      };
    }
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_NativeEngine_renderFrame(void * jarg1) {
  NativeEngine *arg1 = (NativeEngine *) 0 ;
  
  arg1 = (NativeEngine *)jarg1; 
  {
    try {
      (arg1)->renderFrame();
    } catch(std::exception &e) {
      {
        SWIG_CSharpException(SWIG_UnknownError, e.what()); return ; 
      };
    }
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_NativeEngine_mainScene(void * jarg1) {
  void * jresult ;
  NativeEngine *arg1 = (NativeEngine *) 0 ;
  Ogre::SceneManager *result = 0 ;
  
  arg1 = (NativeEngine *)jarg1; 
  {
    try {
      result = (Ogre::SceneManager *)(arg1)->mainScene();
    } catch(std::exception &e) {
      {
        SWIG_CSharpException(SWIG_UnknownError, e.what()); return 0; 
      };
    }
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT /* ctype* out */ QObject* SWIGSTDCALL CSharp_NativeEngine_interfaceRoot(void * jarg1) {
  /* ctype* out */ QObject* jresult ;
  NativeEngine *arg1 = (NativeEngine *) 0 ;
  QObject *result = 0 ;
  
  arg1 = (NativeEngine *)jarg1; 
  {
    try {
      result = (QObject *)(arg1)->interfaceRoot();
    } catch(std::exception &e) {
      {
        SWIG_CSharpException(SWIG_UnknownError, e.what()); return /* null* */ NULL; 
      };
    }
  }
  /* out* */ jresult = result;
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ResourceManager_addZipArchive(char * jarg1, char * jarg2) {
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (char *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    try {
      ResourceManager::addZipArchive((char const *)arg1,(char const *)arg2);
    } catch(std::exception &e) {
      {
        SWIG_CSharpException(SWIG_UnknownError, e.what()); return ; 
      };
    }
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_ResourceManager_addDirectory(char * jarg1, char * jarg2) {
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (char *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    try {
      ResourceManager::addDirectory((char const *)arg1,(char const *)arg2);
    } catch(std::exception &e) {
      {
        SWIG_CSharpException(SWIG_UnknownError, e.what()); return ; 
      };
    }
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_ResourceManager_remove(char * jarg1, char * jarg2) {
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (char *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    try {
      ResourceManager::remove((char const *)arg1,(char const *)arg2);
    } catch(std::exception &e) {
      {
        SWIG_CSharpException(SWIG_UnknownError, e.what()); return ; 
      };
    }
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_ResourceManager_initializeGroup(char * jarg1) {
  char *arg1 = (char *) 0 ;
  
  arg1 = (char *)jarg1; 
  {
    try {
      ResourceManager::initializeGroup((char const *)arg1);
    } catch(std::exception &e) {
      {
        SWIG_CSharpException(SWIG_UnknownError, e.what()); return ; 
      };
    }
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_ResourceManager_read__SWIG_0(char * jarg1, char * jarg2) {
  void * jresult ;
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  QByteArray *result = 0 ;
  
  arg1 = (char *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    try {
      result = (QByteArray *)ResourceManager::read((char const *)arg1,(char const *)arg2);
    } catch(std::exception &e) {
      {
        SWIG_CSharpException(SWIG_UnknownError, e.what()); return 0; 
      };
    }
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_ResourceManager_read__SWIG_1(char * jarg1) {
  void * jresult ;
  char *arg1 = (char *) 0 ;
  QByteArray *result = 0 ;
  
  arg1 = (char *)jarg1; 
  {
    try {
      result = (QByteArray *)ResourceManager::read((char const *)arg1);
    } catch(std::exception &e) {
      {
        SWIG_CSharpException(SWIG_UnknownError, e.what()); return 0; 
      };
    }
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT Ogre::MovableObject * SWIGSTDCALL CSharp_Entity_SWIGUpcast(Ogre::Entity *jarg1) {
    return (Ogre::MovableObject *)jarg1;
}

#ifdef __cplusplus
}
#endif

