#ifndef NATIVEENGINE_GLOBAL_H
#define NATIVEENGINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NATIVEENGINE_LIBRARY)
#  define NATIVEENGINESHARED_EXPORT Q_DECL_EXPORT
#else
#  define NATIVEENGINESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NATIVEENGINE_GLOBAL_H
